export const angularRules = {
	classFiles: {
		'@angular-eslint/contextual-lifecycle': 'error',
		'@angular-eslint/no-async-lifecycle-method': 'error',
		'@angular-eslint/sort-lifecycle-methods': 'error',
		'@angular-eslint/component-class-suffix': 'error',
		'@angular-eslint/directive-class-suffix': 'error',
		'@angular-eslint/component-max-inline-declarations': ['error', { styles: 15 }],
		'@angular-eslint/no-conflicting-lifecycle': 'error',
		'@angular-eslint/no-duplicates-in-metadata-arrays': 'error',
		'@angular-eslint/no-empty-lifecycle-method': 'error',
		'@angular-eslint/no-input-rename': 'off',
		'@angular-eslint/no-inputs-metadata-property': 'error',
		'@angular-eslint/no-lifecycle-call': 'error',
		'@angular-eslint/no-output-native': 'error',
		'@angular-eslint/no-output-on-prefix': 'error',
		'@angular-eslint/no-output-rename': 'error',
		'@angular-eslint/no-outputs-metadata-property': 'error',
		'@angular-eslint/no-pipe-impure': 'warn',
		'@angular-eslint/no-queries-metadata-property': 'error',
		'@angular-eslint/prefer-on-push-component-change-detection': 'error',
		'@angular-eslint/prefer-output-readonly': 'error',
		'@angular-eslint/prefer-standalone': 'off',
		'@angular-eslint/relative-url-prefix': 'error',
		'@angular-eslint/use-component-selector': 'error',
		'@angular-eslint/component-selector': [
			'error',
			{
				type: 'element',
				prefix: '',
				style: 'kebab-case',
			},
		],
		'@angular-eslint/directive-selector': [
			'error',
			{
				type: 'attribute',
				style: 'camelCase',
			},
		],
		'@angular-eslint/consistent-component-styles': ['error', 'string'],
		'@angular-eslint/use-component-view-encapsulation': 'warn',
		'@angular-eslint/use-lifecycle-interface': 'error',
		'@angular-eslint/use-pipe-transform-interface': 'error',
		'@angular-eslint/use-injectable-provided-in': 'off',
		'@angular-eslint/contextual-decorator': 'error',
	},
	templates: {
		'@angular-eslint/template/no-duplicate-attributes': 'error',
		'@angular-eslint/template/alt-text': 'warn',
		'@angular-eslint/template/banana-in-box': 'error',
		'@angular-eslint/template/button-has-type': 'warn',
		'@angular-eslint/template/click-events-have-key-events': 'off',
		'@angular-eslint/template/conditional-complexity': [
			'error',
			{
				maxComplexity: 9,
			},
		],
		'@angular-eslint/template/cyclomatic-complexity': [
			'error',
			{
				maxComplexity: 9,
			},
		],
		'@angular-eslint/template/elements-content': 'off',
		'@angular-eslint/template/eqeqeq': 'error',
		'@angular-eslint/template/i18n': 'off',
		'@angular-eslint/template/label-has-associated-control': 'off',
		'@angular-eslint/template/mouse-events-have-key-events': 'error',
		'@angular-eslint/template/no-any': 'error',
		'@angular-eslint/template/no-autofocus': 'error',
		'@angular-eslint/template/no-distracting-elements': 'error',
		'@angular-eslint/template/no-inline-styles': 'off',
		'@angular-eslint/template/no-interpolation-in-attributes': 'error',
		'@angular-eslint/template/no-positive-tabindex': 'error',
		'@angular-eslint/template/prefer-ngsrc': 'off',
		'@angular-eslint/template/use-track-by-function': 'error',
		'@angular-eslint/template/no-negated-async': 'error',
		'@angular-eslint/template/prefer-control-flow': 'error',
		'@angular-eslint/template/attributes-order': 'error',
		'@angular-eslint/template/prefer-self-closing-tags': 'error',
		'@angular-eslint/template/no-call-expression': 'off',
		'@angular-eslint/template/interactive-supports-focus': 'off',
	},
	tests: {
		'@angular-eslint/prefer-on-push-component-change-detection': 'off',
		'@angular-eslint/component-max-inline-declarations': 'off',
		'@angular-eslint/use-component-selector': 'off',
	},
};
